name: Npm Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🍞 Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: 📦 Install packages and prebuild
        run: bun install --frozen-lockfile
        shell: bash

      - name: 🚀 Publish
        run: npm publish --access public
        env:
          CI: true
